### ISSUE TITLE
Cannot click edit,Also some buttons cannot be displayed normally

### ISSUE THREAD

**Issue by iNyanPasu** [UltimateDoge5/PhantomShapes#3]
I am using PhantomShapes version 1.0.7,minecraft version 1.20.4
![111](https://github.com/UltimateDoge5/PhantomShapes/assets/75481306/5bb474a5-26ad-456f-b542-bae01901fad1)

**Comment by UltimateDoge5** [comment]
Thanks for the feedback!
This is a problem that I've actually noticed myself but decided not pursue it at that time and then kind of forgot about it 😅

I'll do some research about the gui in mc, need to come up with some smart auto-positioning system instead of setting fixed label sizes and positions.

**Comment by UltimateDoge5** [comment]
You can get the newest mod version from [modrinth](https://modrinth.com/mod/phantomshapes/versions). If you still have any issues feel free to come back to this issue.
